//
// Autogenerated by Thrift Compiler (0.9.2)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./ActiveBundle_types');
//HELPER FUNCTIONS AND STRUCTURES

ABService_getValue_args = function(args) {
  this.request = null;
  this.signature = null;
  this.certificate = null;
  if (args) {
    if (args.request !== undefined) {
      this.request = args.request;
    }
    if (args.signature !== undefined) {
      this.signature = args.signature;
    }
    if (args.certificate !== undefined) {
      this.certificate = args.certificate;
    }
  }
};
ABService_getValue_args.prototype = {};
ABService_getValue_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.request = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.signature = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.certificate = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ABService_getValue_args.prototype.write = function(output) {
  output.writeStructBegin('ABService_getValue_args');
  if (this.request !== null && this.request !== undefined) {
    output.writeFieldBegin('request', Thrift.Type.STRING, 1);
    output.writeString(this.request);
    output.writeFieldEnd();
  }
  if (this.signature !== null && this.signature !== undefined) {
    output.writeFieldBegin('signature', Thrift.Type.STRING, 2);
    output.writeString(this.signature);
    output.writeFieldEnd();
  }
  if (this.certificate !== null && this.certificate !== undefined) {
    output.writeFieldBegin('certificate', Thrift.Type.STRING, 3);
    output.writeString(this.certificate);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ABService_getValue_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
ABService_getValue_result.prototype = {};
ABService_getValue_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ABService_getValue_result.prototype.write = function(output) {
  output.writeStructBegin('ABService_getValue_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ABServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ABServiceClient.prototype = {};
ABServiceClient.prototype.seqid = function() { return this._seqid; }
ABServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
ABServiceClient.prototype.getValue = function(request, signature, certificate, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getValue(request, signature, certificate);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getValue(request, signature, certificate);
  }
};

ABServiceClient.prototype.send_getValue = function(request, signature, certificate) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getValue', Thrift.MessageType.CALL, this.seqid());
  var args = new ABService_getValue_args();
  args.request = request;
  args.signature = signature;
  args.certificate = certificate;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ABServiceClient.prototype.recv_getValue = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ABService_getValue_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getValue failed: unknown result');
};
ABServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
ABServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

ABServiceProcessor.prototype.process_getValue = function(seqid, input, output) {
  var args = new ABService_getValue_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getValue.length === 3) {
    Q.fcall(this._handler.getValue, args.request, args.signature, args.certificate)
      .then(function(result) {
        var result = new ABService_getValue_result({success: result});
        output.writeMessageBegin("getValue", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new ABService_getValue_result(err);
        output.writeMessageBegin("getValue", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getValue(args.request, args.signature, args.certificate,  function (err, result) {
      var result = new ABService_getValue_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getValue", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

